// Compatibility facade. Domain code should import from its module directly.
export { default } from '../shared/api/client'
export { authApi, userApi } from '../modules/identity/api'
export { threadApi, postApi, moderationApi, categoryApi } from '../modules/community/api'
export { richTextApi } from '../modules/richtext/api'
export { scheduleApi } from '../modules/schedule/api'
export { homeApi, webThemeApi } from '../modules/appearance/api'
export { uiRuntimeApi } from '../modules/plugin-runtime/api'
export { spaceApi } from '../modules/space/api'
export { healthApi } from '../modules/platform/api'
