-- 仅供空隔离库演练。生产库应保持稳定合同名称并使用 forward-fix。
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_user_storage_accounts_used') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_storage_accounts_used_bytes_check') THEN EXECUTE 'ALTER TABLE user_storage_accounts RENAME CONSTRAINT chk_user_storage_accounts_used TO user_storage_accounts_used_bytes_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_user_storage_accounts_reserved') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_storage_accounts_reserved_bytes_check') THEN EXECUTE 'ALTER TABLE user_storage_accounts RENAME CONSTRAINT chk_user_storage_accounts_reserved TO user_storage_accounts_reserved_bytes_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_user_storage_accounts_version') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_storage_accounts_version_check') THEN EXECUTE 'ALTER TABLE user_storage_accounts RENAME CONSTRAINT chk_user_storage_accounts_version TO user_storage_accounts_version_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_storage_objects_provider') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='storage_objects_provider_check') THEN EXECUTE 'ALTER TABLE storage_objects RENAME CONSTRAINT chk_storage_objects_provider TO storage_objects_provider_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_storage_objects_size') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='storage_objects_size_bytes_check') THEN EXECUTE 'ALTER TABLE storage_objects RENAME CONSTRAINT chk_storage_objects_size TO storage_objects_size_bytes_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_storage_objects_status') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='storage_objects_status_check') THEN EXECUTE 'ALTER TABLE storage_objects RENAME CONSTRAINT chk_storage_objects_status TO storage_objects_status_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_storage_objects_version') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='storage_objects_version_check') THEN EXECUTE 'ALTER TABLE storage_objects RENAME CONSTRAINT chk_storage_objects_version TO storage_objects_version_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_user_storage_reservations_bytes') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_storage_reservations_reserved_bytes_check') THEN EXECUTE 'ALTER TABLE user_storage_reservations RENAME CONSTRAINT chk_user_storage_reservations_bytes TO user_storage_reservations_reserved_bytes_check'; END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_user_storage_reservations_status') AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_storage_reservations_status_check') THEN EXECUTE 'ALTER TABLE user_storage_reservations RENAME CONSTRAINT chk_user_storage_reservations_status TO user_storage_reservations_status_check'; END IF;
END $$;
