import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"版主管理 API","description":"","frontmatter":{},"headers":[],"relativePath":"api/moderation.md","filePath":"api/moderation.md","lastUpdated":null}');
const _sfc_main = { name: "api/moderation.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="版主管理-api" tabindex="-1">版主管理 API <a class="header-anchor" href="#版主管理-api" aria-label="Permalink to &quot;版主管理 API&quot;">​</a></h1><h2 id="授权模型" tabindex="-1">授权模型 <a class="header-anchor" href="#授权模型" aria-label="Permalink to &quot;授权模型&quot;">​</a></h2><p>版主不是全站角色。每个版主必须绑定一个或多个 <code>category</code> scope，只能治理被分配版块中的内容。</p><p>当前治理动作：</p><table tabindex="0"><thead><tr><th>权限</th><th>动作</th></tr></thead><tbody><tr><td><code>thread:pin</code></td><td>置顶和取消置顶。</td></tr><tr><td><code>thread:lock</code></td><td>锁定和解锁。</td></tr><tr><td><code>post:delete</code></td><td>删除回复。</td></tr></tbody></table><p>主题操作从 <code>threads.category_id</code> 读取版块；回复操作先读取所属主题。请求体中的版块值不会作为授权依据。</p><h2 id="管理员配置版主" tabindex="-1">管理员配置版主 <a class="header-anchor" href="#管理员配置版主" aria-label="Permalink to &quot;管理员配置版主&quot;">​</a></h2><p>列出所有版主：</p><div class="language-http vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">http</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">GET</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /api/v1/moderation/admin/moderators</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">Authorization</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> Bearer &lt;admin_token&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>读取一个用户：</p><div class="language-http vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">http</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">GET</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /api/v1/moderation/admin/moderators/:user_id</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>完整替换其版块范围：</p><div class="language-http vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">http</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">PUT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /api/v1/moderation/admin/moderators/:user_id</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">Content-Type</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> application/json</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><div class="language-json vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;category_ids&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;1000000000000000004&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">    &quot;1783048438434995264&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>空数组会撤销该用户全部版主 scope。通用 <code>/users/:id/roles</code> 接口拒绝创建没有版块范围的全局版主。</p><h2 id="当前用户可执行动作" tabindex="-1">当前用户可执行动作 <a class="header-anchor" href="#当前用户可执行动作" aria-label="Permalink to &quot;当前用户可执行动作&quot;">​</a></h2><div class="language-http vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">http</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">GET</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /api/v1/moderation/me?thread_id=&lt;thread_id&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">Authorization</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> Bearer &lt;access_token&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>响应中的 <code>actions</code> 由后端根据插件状态、动作开关、角色权限和版块 scope 计算。前端只应显示返回为 <code>true</code> 的按钮。</p><h2 id="治理接口" tabindex="-1">治理接口 <a class="header-anchor" href="#治理接口" aria-label="Permalink to &quot;治理接口&quot;">​</a></h2><table tabindex="0"><thead><tr><th>方法</th><th>路径</th><th>说明</th></tr></thead><tbody><tr><td><code>POST</code></td><td><code>/moderation/threads/:id/pin</code></td><td>置顶主题。</td></tr><tr><td><code>POST</code></td><td><code>/moderation/threads/:id/unpin</code></td><td>取消置顶。</td></tr><tr><td><code>POST</code></td><td><code>/moderation/threads/:id/lock</code></td><td>锁定主题。</td></tr><tr><td><code>POST</code></td><td><code>/moderation/threads/:id/unlock</code></td><td>解锁主题。</td></tr><tr><td><code>DELETE</code></td><td><code>/moderation/threads/:thread_id/posts/:post_id</code></td><td>删除回复。</td></tr></tbody></table><p>跨版块请求返回 <code>403</code>。插件整体停用并重启后返回 <code>503/71001</code>。</p><h2 id="插件配置热更新" tabindex="-1">插件配置热更新 <a class="header-anchor" href="#插件配置热更新" aria-label="Permalink to &quot;插件配置热更新&quot;">​</a></h2><p><code>category-moderation</code> 是系统级插件，整体启用或停用需要重启 API。但以下动作开关保存后立即作用于下一次授权检查：</p><div class="language-json vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;allow_pin&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;allow_lock&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;allow_delete_post&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>配置通过：</p><div class="language-http vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">http</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">PUT</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> /api/v1/plugins/category-moderation/config</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>旧页面尚未刷新时可能仍显示按钮，但后端会立即拒绝已经关闭的动作。刷新帖子详情后按钮会同步。</p><h2 id="审计" tabindex="-1">审计 <a class="header-anchor" href="#审计" aria-label="Permalink to &quot;审计&quot;">​</a></h2><p>版主范围变更、置顶、锁定和删除回复写入 <code>audit_logs</code>。插件停用不会删除 scope 或历史审计。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("api/moderation.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const moderation = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  moderation as default
};
