import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"配置与端口","description":"","frontmatter":{},"headers":[],"relativePath":"deployment/configuration.md","filePath":"deployment/configuration.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "deployment/configuration.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="配置与端口" tabindex="-1">配置与端口 <a class="header-anchor" href="#配置与端口" aria-label="Permalink to &quot;配置与端口&quot;">​</a></h1><h2 id="配置加载顺序" tabindex="-1">配置加载顺序 <a class="header-anchor" href="#配置加载顺序" aria-label="Permalink to &quot;配置加载顺序&quot;">​</a></h2><p>后端按以下顺序读取配置：</p><ol><li>当前进程环境变量。</li><li>项目根目录 <code>.env</code>。</li><li>代码中的开发默认值。</li></ol><p><code>.env</code> 不应提交到 Git。新增非敏感示例项时同步更新 <code>.env.example</code>。</p><h2 id="数据库" tabindex="-1">数据库 <a class="header-anchor" href="#数据库" aria-label="Permalink to &quot;数据库&quot;">​</a></h2><p>默认连接字符串：</p><div class="language-dotenv vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">dotenv</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">DATABASE_DSN</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">postgres://campusos:campusos_dev@localhost:5432/campusos?sslmode=disable</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>如果宿主机 <code>5432</code> 已被占用，可以同时修改：</p><div class="language-dotenv vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">dotenv</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">POSTGRES_PORT</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">5433</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">DATABASE_DSN</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">postgres://campusos:campusos_dev@localhost:5433/campusos?sslmode=disable</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p><code>POSTGRES_PORT</code> 只控制 Docker 暴露端口，不会自动重写 <code>DATABASE_DSN</code>。</p><h2 id="服务端口" tabindex="-1">服务端口 <a class="header-anchor" href="#服务端口" aria-label="Permalink to &quot;服务端口&quot;">​</a></h2><table tabindex="0"><thead><tr><th>变量</th><th>默认值</th><th>说明</th></tr></thead><tbody><tr><td><code>SERVER_PORT</code></td><td><code>8080</code></td><td>API HTTP 端口。</td></tr><tr><td><code>WEB_PORT</code></td><td><code>3000</code></td><td>用户前台开发端口。</td></tr><tr><td><code>ADMIN_PORT</code></td><td><code>3001</code></td><td>管理后台开发端口。</td></tr><tr><td><code>DOCS_PORT</code></td><td><code>3002</code></td><td>官方文档开发端口。</td></tr><tr><td><code>HOST_API_PORT</code></td><td><code>18080</code></td><td>插件 Host API 端口。</td></tr><tr><td><code>PGADMIN_PORT</code></td><td><code>5050</code></td><td>pgAdmin 页面端口。</td></tr></tbody></table><p>Admin 中的官方文档链接默认指向 <code>http://localhost:3002</code>。独立部署文档站后，在构建 Admin 前设置：</p><div class="language-dotenv vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">dotenv</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">VITE_DOCS_URL</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">https://docs.example.edu</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">VITE_GITHUB_URL</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">https://github.com/javencpdd/CampusOS</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="插件目录" tabindex="-1">插件目录 <a class="header-anchor" href="#插件目录" aria-label="Permalink to &quot;插件目录&quot;">​</a></h2><div class="language-dotenv vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">dotenv</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">PLUGINS_DIR</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">data/plugins</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">PLUGIN_DATA_DIR</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">data/plugin_data</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><ul><li><code>PLUGINS_DIR</code>：Manager 扫描插件实现的根目录。</li><li><code>PLUGIN_DATA_DIR</code>：插件 KV 和运行数据根目录。</li></ul><p>不要把两个变量指向同一目录。</p><h2 id="本地日志" tabindex="-1">本地日志 <a class="header-anchor" href="#本地日志" aria-label="Permalink to &quot;本地日志&quot;">​</a></h2><div class="language-dotenv vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">dotenv</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">CAMPUSOS_LOG_DIR</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">.campusos/logs</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>平台日志接口只允许读取预先声明的日志源，不接受任意文件路径。</p><h2 id="敏感配置" tabindex="-1">敏感配置 <a class="header-anchor" href="#敏感配置" aria-label="Permalink to &quot;敏感配置&quot;">​</a></h2><p>以下信息不能写入仓库、插件包或前端构建产物：</p><ul><li>数据库生产密码。</li><li>JWT 密钥和 API Key。</li><li>Webhook 签名密钥。</li><li>AI provider token。</li><li>第三方平台凭据。</li></ul><p>生产环境应由部署平台的 Secret 管理能力注入，而不是复用开发 <code>.env</code>。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("deployment/configuration.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const configuration = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  configuration as default
};
