import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"构建与发布","description":"","frontmatter":{},"headers":[],"relativePath":"deployment/release.md","filePath":"deployment/release.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "deployment/release.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="构建与发布" tabindex="-1">构建与发布 <a class="header-anchor" href="#构建与发布" aria-label="Permalink to &quot;构建与发布&quot;">​</a></h1><h2 id="当前交付边界" tabindex="-1">当前交付边界 <a class="header-anchor" href="#当前交付边界" aria-label="Permalink to &quot;当前交付边界&quot;">​</a></h2><p>CampusOS 当前具备开发环境、前端生产构建和后端二进制构建能力，但尚未形成经过完整验收的生产级容器镜像与高可用部署方案。以下流程适合测试环境和发布预检，公网部署还需要 TLS、密钥管理、备份、监控和安全加固。</p><h2 id="构建后端" tabindex="-1">构建后端 <a class="header-anchor" href="#构建后端" aria-label="Permalink to &quot;构建后端&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>产物默认位于：</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>bin/campusos-server</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>运行前必须提供数据库、Redis、NATS 和必要环境变量。</p><h2 id="构建前端" tabindex="-1">构建前端 <a class="header-anchor" href="#构建前端" aria-label="Permalink to &quot;构建前端&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> web</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> &amp;&amp; </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ../admin</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> &amp;&amp; </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ../docs-site</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> &amp;&amp; </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>产物：</p><table tabindex="0"><thead><tr><th>项目</th><th>默认目录</th></tr></thead><tbody><tr><td>Web</td><td><code>web/dist/</code></td></tr><tr><td>Admin</td><td><code>admin/dist/</code></td></tr><tr><td>Docs</td><td><code>docs-site/.vitepress/dist/</code></td></tr></tbody></table><p>这些目录可以交给 Nginx、Caddy 或对象存储静态托管。Web 和 Admin 的 <code>/api</code> 请求需要反向代理到 CampusOS API；Docs 是纯静态站点，不依赖 API。</p><h2 id="发布前-migration" tabindex="-1">发布前 migration <a class="header-anchor" href="#发布前-migration" aria-label="Permalink to &quot;发布前 migration&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> migrate-status</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> migrate-up</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> migrate-status</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>执行 migration 前应备份 PostgreSQL 和 <code>data/</code>。不要直接修改已经在其他环境应用的历史 migration；新增变更使用新的递增版本。</p><h2 id="反向代理边界" tabindex="-1">反向代理边界 <a class="header-anchor" href="#反向代理边界" aria-label="Permalink to &quot;反向代理边界&quot;">​</a></h2><p>建议使用不同域名或明确路径：</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>community.example.edu   -&gt; web/dist</span></span>
<span class="line"><span>admin.example.edu       -&gt; admin/dist</span></span>
<span class="line"><span>docs.example.edu        -&gt; docs-site/.vitepress/dist</span></span>
<span class="line"><span>api.example.edu         -&gt; campusos-server:8080</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>Admin 构建时将 <code>VITE_DOCS_URL</code> 指向公开文档地址。文档站独立后无需改动 API 或数据库。</p><h2 id="发布检查清单" tabindex="-1">发布检查清单 <a class="header-anchor" href="#发布检查清单" aria-label="Permalink to &quot;发布检查清单&quot;">​</a></h2><ol><li>Go 全量测试通过。</li><li>Web、Admin、Docs 构建通过。</li><li>migration 状态与仓库一致。</li><li>默认管理员密码已修改。</li><li>数据库、<code>data/</code> 和配置备份已验证可恢复。</li><li>API 只通过 TLS 暴露，CORS 和可信代理配置明确。</li><li>插件包来源、权限和 checksum 已人工复核。</li><li>Admin、平台日志和 pgAdmin 不向非管理员开放。</li></ol><h2 id="回滚原则" tabindex="-1">回滚原则 <a class="header-anchor" href="#回滚原则" aria-label="Permalink to &quot;回滚原则&quot;">​</a></h2><p>代码回滚不等于数据回滚。涉及 migration 或插件数据格式时，需要在发布前写明：</p><ul><li>兼容的旧版本范围。</li><li>数据回填是否可逆。</li><li>down migration 的风险。</li><li><code>data/</code> 文件是否需要同步恢复。</li></ul><p>优先采用向前修复和兼容读取，避免在没有备份验证的情况下直接回滚结构性 migration。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("deployment/release.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const release = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  release as default
};
