import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"系统架构","description":"","frontmatter":{},"headers":[],"relativePath":"guide/architecture.md","filePath":"guide/architecture.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "guide/architecture.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="系统架构" tabindex="-1">系统架构 <a class="header-anchor" href="#系统架构" aria-label="Permalink to &quot;系统架构&quot;">​</a></h1><h2 id="请求链路" tabindex="-1">请求链路 <a class="header-anchor" href="#请求链路" aria-label="Permalink to &quot;请求链路&quot;">​</a></h2><p>浏览器不直接访问数据库或插件数据。用户前台和管理后台统一调用 <code>/api/v1</code>，由后端完成认证、权限、对象归属和数据范围检查。</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>browser</span></span>
<span class="line"><span>  -&gt; Gin middleware</span></span>
<span class="line"><span>  -&gt; identity and permission check</span></span>
<span class="line"><span>  -&gt; domain service</span></span>
<span class="line"><span>  -&gt; PostgreSQL / cache / local file storage</span></span>
<span class="line"><span>  -&gt; event bus and plugin runtime</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>前端隐藏按钮只用于改善体验，不是安全边界。即使客户端手工构造请求，后端仍必须重新授权。</p><h2 id="后端模块" tabindex="-1">后端模块 <a class="header-anchor" href="#后端模块" aria-label="Permalink to &quot;后端模块&quot;">​</a></h2><table tabindex="0"><thead><tr><th>模块</th><th>职责</th></tr></thead><tbody><tr><td><code>internal/core/identity</code></td><td>用户、账号、JWT、角色和权限。</td></tr><tr><td><code>internal/community</code></td><td>版块、帖子、回复、标签和社区事件。</td></tr><tr><td><code>internal/moderation</code></td><td>版块版主作用域、治理动作和审计。</td></tr><tr><td><code>internal/plugin</code></td><td>Manager、manifest、Runtime、插件包、配置和日志。</td></tr><tr><td><code>internal/plugin/hostapi</code></td><td>插件访问主系统能力的受控边界。</td></tr><tr><td><code>internal/space</code></td><td>个人主页、头像、用户文件和主页所有者风格包。</td></tr><tr><td><code>internal/stylepack</code>、<code>internal/webtheme</code></td><td>目标作用域筛查、沙箱特效声明和管理员系统主题目录。</td></tr><tr><td><code>internal/richtext</code></td><td>富文本草稿、清洗、发布和图片资产。</td></tr><tr><td><code>internal/schedule</code></td><td>学期课表、日历计算和表格导入。</td></tr><tr><td><code>internal/webhook</code>、<code>internal/mcp</code>、<code>internal/message</code></td><td>低风险外部集成。</td></tr></tbody></table><h2 id="权限模型" tabindex="-1">权限模型 <a class="header-anchor" href="#权限模型" aria-label="Permalink to &quot;权限模型&quot;">​</a></h2><p>敏感操作按以下顺序判断：</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>authentication</span></span>
<span class="line"><span>  -&gt; resource:action</span></span>
<span class="line"><span>  -&gt; ownership or scope</span></span>
<span class="line"><span>  -&gt; operation constraints</span></span>
<span class="line"><span>  -&gt; audit</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p><code>member</code> 是有效登录用户的隐式基础角色；管理员使用全局授权；版主必须绑定一个或多个版块。版主操作帖子或回复时，后端从目标资源读取真实 <code>category_id</code>，不信任客户端提交的版块值。</p><h2 id="插件边界" tabindex="-1">插件边界 <a class="header-anchor" href="#插件边界" aria-label="Permalink to &quot;插件边界&quot;">​</a></h2><p>CampusOS 当前支持三种 Runtime：</p><table tabindex="0"><thead><tr><th>Runtime</th><th>运行方式</th><th>适用场景</th></tr></thead><tbody><tr><td><code>builtin</code></td><td>业务实现编译在 CampusOS 后端中，插件目录保存 manifest 和配置。</td><td>随系统部署的默认能力。</td></tr><tr><td><code>wasm</code></td><td>由 wazero 在受控 Runtime 中加载模块。</td><td>小型事件逻辑和隔离执行。</td></tr><tr><td><code>grpc</code></td><td>外部进程通过 gRPC 与主系统通信。</td><td>复杂依赖和独立服务。</td></tr></tbody></table><p>插件不能直接获得主系统全部能力。Host API 根据插件 manifest 中声明的权限进行默认拒绝检查。</p><h2 id="数据持久化" tabindex="-1">数据持久化 <a class="header-anchor" href="#数据持久化" aria-label="Permalink to &quot;数据持久化&quot;">​</a></h2><table tabindex="0"><thead><tr><th>数据</th><th>保存位置</th></tr></thead><tbody><tr><td>用户、帖子、权限、插件元数据和审计</td><td>PostgreSQL。</td></tr><tr><td>列表缓存和临时状态</td><td>Redis。</td></tr><tr><td>领域事件</td><td>NATS 与进程内事件总线。</td></tr><tr><td>插件代码</td><td><code>data/plugins/&lt;plugin&gt;/</code>。</td></tr><tr><td>插件运行数据</td><td><code>data/plugin_data/&lt;plugin&gt;/</code>。</td></tr><tr><td>用户文件</td><td><code>data/personal-space/&lt;user_id&gt;/</code>。</td></tr><tr><td>开发日志</td><td><code>.campusos/logs/</code>。</td></tr></tbody></table><p>数据库 migration 当前没有统一声明 PostgreSQL 外键，部分关系仍由索引和服务层约束表达。修改 schema 前应先运行数据质量检查和 migration 验证。</p><h2 id="页面扩展安全" tabindex="-1">页面扩展安全 <a class="header-anchor" href="#页面扩展安全" aria-label="Permalink to &quot;页面扩展安全&quot;">​</a></h2><p>个人主页、首页和完整用户前台风格包必须通过后端筛查。HTML 事件处理器、不安全 URL、路径逃逸和危险 CSS 会被拒绝；可选 JavaScript 仅在无同源、无 DOM、无存储和无任意网络权限的 <code>sandbox-worker.v1</code> 中执行。CampusStyleSDK 只代理 manifest 声明的只读能力，并继续执行主页所有者绑定和用户私有能力授权。</p><p>下一步可阅读 <a href="/reference/data-layout">数据目录</a> 或 <a href="/plugins/overview">插件体系</a>。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/architecture.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const architecture = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  architecture as default
};
