import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"项目介绍","description":"","frontmatter":{},"headers":[],"relativePath":"guide/introduction.md","filePath":"guide/introduction.md","lastUpdated":1783870868000}');
const _sfc_main = { name: "guide/introduction.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="项目介绍" tabindex="-1">项目介绍 <a class="header-anchor" href="#项目介绍" aria-label="Permalink to &quot;项目介绍&quot;">​</a></h1><h2 id="campusos-是什么" tabindex="-1">CampusOS 是什么 <a class="header-anchor" href="#campusos-是什么" aria-label="Permalink to &quot;CampusOS 是什么&quot;">​</a></h2><p>CampusOS 面向校园社区场景，把论坛、个人空间和插件平台放在同一套系统中。用户可以按版块发布普通文本帖子或受控富文本文章、回复和管理自己的内容；管理员可以管理用户、版块、插件、集成和平台运行信息。</p><p>项目当前稳定开发基线为 <code>v0.7.0</code>。v7 已完成模块化单体边界优化：Module Registry 管理 Core 生命周期，Feature Registry 管理内置功能，Plugin Platform 通过兼容 Facade 管理外部扩展，Resource Repository 管理无运行时资源包。现有 API、数据库、插件和前端合同保持兼容。</p><h2 id="已实现能力" tabindex="-1">已实现能力 <a class="header-anchor" href="#已实现能力" aria-label="Permalink to &quot;已实现能力&quot;">​</a></h2><table tabindex="0"><thead><tr><th>领域</th><th>当前能力</th></tr></thead><tbody><tr><td>社区</td><td>注册登录、版块、默认标签、普通帖子、富文本图文文章、回复楼层、私密帖子。</td></tr><tr><td>用户空间</td><td>公开个人主页、头像、每用户本地空间、风格包、内容同步。</td></tr><tr><td>个人课表</td><td>独立学期 JSON、第一周设置、周课表、日历和 Excel/CSV/JSON 导入。</td></tr><tr><td>管理后台</td><td>用户、帖子、版块、版主、插件、集成、日志和数据库架构说明。</td></tr><tr><td>插件运行时</td><td>Built-in、Wasm、gRPC，支持事件、Host API、配置、日志和 KV。</td></tr><tr><td>插件包</td><td>CLI 初始化、检查、打包和安装；Admin 预检、导入、导出和覆盖更新。</td></tr><tr><td>低风险集成</td><td>AI Gateway、Webhook、内部 MCP-like 只读工具和 Message local adapter。</td></tr></tbody></table><h2 id="当前没有承诺的能力" tabindex="-1">当前没有承诺的能力 <a class="header-anchor" href="#当前没有承诺的能力" aria-label="Permalink to &quot;当前没有承诺的能力&quot;">​</a></h2><p>以下项目仍属于后续工作，不能把现有实现描述成已经完成：</p><ul><li>标准 MCP Server。</li><li>Discord、OneBot v11 等真实外部消息适配器。</li><li>公网插件市场和自动信任第三方插件。</li><li>在主页面同源执行任意 JavaScript 的风格包；动态特效只允许使用受筛查的 <code>sandbox-worker.v1</code>。</li><li>完整的容器化生产交付、跨区域高可用或零停机升级。</li></ul><h2 id="技术组成" tabindex="-1">技术组成 <a class="header-anchor" href="#技术组成" aria-label="Permalink to &quot;技术组成&quot;">​</a></h2><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>web (Vue 3, :3000) ---------\\</span></span>
<span class="line"><span>                              -&gt; API (Go + Gin, :8080) -&gt; PostgreSQL</span></span>
<span class="line"><span>admin (Vue 3, :3001) -------/                         -&gt; Redis / NATS</span></span>
<span class="line"><span>docs-site (VitePress, :3002)                          -&gt; data/</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><table tabindex="0"><thead><tr><th>组件</th><th>作用</th></tr></thead><tbody><tr><td><code>cmd/server</code></td><td>API 服务入口。</td></tr><tr><td><code>internal/</code></td><td>Identity、Community、Plugin、Space、Richtext、Schedule 等领域模块。</td></tr><tr><td><code>web/</code></td><td>普通用户前台。</td></tr><tr><td><code>admin/</code></td><td>管理员前台。</td></tr><tr><td><code>docs-site/</code></td><td>可独立迁移的官方文档前端。</td></tr><tr><td><code>data/plugins/</code></td><td>插件实现、manifest 和运行入口。</td></tr><tr><td><code>data/plugin_data/</code></td><td>插件运行数据和可编辑风格包源码。</td></tr><tr><td><code>data/personal-space/</code></td><td>每个用户的本地文件和图片。</td></tr></tbody></table><h2 id="推荐阅读顺序" tabindex="-1">推荐阅读顺序 <a class="header-anchor" href="#推荐阅读顺序" aria-label="Permalink to &quot;推荐阅读顺序&quot;">​</a></h2><ol><li><a href="/guide/architecture">系统架构</a>：了解模块和安全边界。</li><li><a href="/deployment/development">开发环境</a>：在本机启动完整系统。</li><li><a href="/api/overview">接口约定</a>：理解认证、响应和错误。</li><li><a href="/plugins/overview">插件体系</a>：区分 Runtime、生命周期和数据目录。</li><li><a href="/plugins/create-first-plugin">编写第一个插件</a>：完成一次插件闭环。</li></ol><h2 id="仓库与许可" tabindex="-1">仓库与许可 <a class="header-anchor" href="#仓库与许可" aria-label="Permalink to &quot;仓库与许可&quot;">​</a></h2><p>源码位于 <a href="https://github.com/javencpdd/CampusOS" target="_blank" rel="noreferrer">GitHub</a>。具体许可条款以仓库根目录的 <code>LICENSE</code> 为准。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/introduction.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const introduction = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  introduction as default
};
