import { ssrRenderAttrs, ssrRenderAttr, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const _imports_0 = "/campusos-admin.png";
const __pageData = JSON.parse('{"title":"CampusOS 官方文档","description":"","frontmatter":{},"headers":[],"relativePath":"index.md","filePath":"index.md","lastUpdated":null}');
const _sfc_main = { name: "index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="campusos-官方文档" tabindex="-1">CampusOS 官方文档 <a class="header-anchor" href="#campusos-官方文档" aria-label="Permalink to &quot;CampusOS 官方文档&quot;">​</a></h1><p>CampusOS 是一个基于 Go、Gin、Vue 3 和 PostgreSQL 的校园社区系统，同时提供用户社区、管理后台、个人空间、受控富文本、个人课表和可扩展插件运行时。</p><div class="status-line"><code>v0.6.8-dev</code><code>Go + Gin</code><code>Vue 3</code><code>PostgreSQL</code><code>Built-in / Wasm / gRPC</code></div><div class="doc-link-grid"><a href="/guide/introduction"><strong>了解 CampusOS</strong><span>项目能力、技术边界、仓库结构和建议阅读顺序。</span></a><a href="/deployment/development"><strong>启动开发环境</strong><span>安装依赖、准备配置、运行 migration 并启动四个开发服务。</span></a><a href="/api/overview"><strong>调用 HTTP API</strong><span>认证、响应包络、错误处理、接口分组和当前契约边界。</span></a><a href="/plugins/create-first-plugin"><strong>编写插件</strong><span>从脚手架到 manifest、测试、打包、预检和管理端导入。</span></a></div><h2 id="当前界面" tabindex="-1">当前界面 <a class="header-anchor" href="#当前界面" aria-label="Permalink to &quot;当前界面&quot;">​</a></h2><p>下图来自当前 CampusOS 管理端。官方文档站与管理端分开部署，不需要管理员登录，后续可以直接迁移到独立仓库或文档域名。</p><img class="product-shot"${ssrRenderAttr("src", _imports_0)} alt="CampusOS 管理后台登录界面"><h2 id="最短启动路径" tabindex="-1">最短启动路径 <a class="header-anchor" href="#最短启动路径" aria-label="Permalink to &quot;最短启动路径&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cp</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> .env.example</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> .env</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">STOP_EXISTING</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev-all</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>默认开发地址：</p><table tabindex="0"><thead><tr><th>服务</th><th>地址</th></tr></thead><tbody><tr><td>用户前台</td><td><code>http://localhost:3000</code></td></tr><tr><td>管理后台</td><td><code>http://localhost:3001</code></td></tr><tr><td>官方文档</td><td><code>http://localhost:3002</code></td></tr><tr><td>后端 API</td><td><code>http://localhost:8080/api/v1</code></td></tr></tbody></table><div class="warning custom-block"><p class="custom-block-title">当前开发边界</p><p>CampusOS 仍处于开发阶段。当前 Docker Compose 主要提供 PostgreSQL、Redis、NATS 和 pgAdmin 等开发依赖，不应把本文中的本地配置直接用于公网生产环境。</p></div><h2 id="参与开发" tabindex="-1">参与开发 <a class="header-anchor" href="#参与开发" aria-label="Permalink to &quot;参与开发&quot;">​</a></h2><ul><li><a href="https://github.com/javencpdd/CampusOS" target="_blank" rel="noreferrer">GitHub 仓库</a></li><li><a href="/plugins/create-first-plugin">编写第一个插件</a></li><li><a href="/deployment/release">构建与发布</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
