import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"备份、恢复与版本验收","description":"","frontmatter":{},"headers":[],"relativePath":"operations/recovery.md","filePath":"operations/recovery.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "operations/recovery.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="备份、恢复与版本验收" tabindex="-1">备份、恢复与版本验收 <a class="header-anchor" href="#备份、恢复与版本验收" aria-label="Permalink to &quot;备份、恢复与版本验收&quot;">​</a></h1><h2 id="单节点备份" tabindex="-1">单节点备份 <a class="header-anchor" href="#单节点备份" aria-label="Permalink to &quot;单节点备份&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> backup</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">./scripts/restore.sh</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> verify</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> backups/campusos-backup-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">.tar.gz</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>备份包含 PostgreSQL dump、migration、插件代码、插件数据和版本快照、个人空间、图片及本地配置，并为内部文件生成 SHA-256 清单。备份可能包含密钥，不得上传公共仓库。</p><h2 id="隔离恢复演练" tabindex="-1">隔离恢复演练 <a class="header-anchor" href="#隔离恢复演练" aria-label="Permalink to &quot;隔离恢复演练&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> restore-drill</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>演练创建临时数据库，恢复并读取用户、帖子、插件和 migration，再检查插件与个人空间文件；结束后删除临时数据库，不覆盖当前实例。</p><p>生产恢复必须先停止 API 和写入流量，再由维护者执行：</p><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">./scripts/restore.sh</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> apply</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> &lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">backup.tar.g</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">z</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">&gt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --confirm</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> migrate-up</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">make</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> database-check</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="插件回滚" tabindex="-1">插件回滚 <a class="header-anchor" href="#插件回滚" aria-label="Permalink to &quot;插件回滚&quot;">​</a></h2><p>用户级插件在覆盖更新前自动保存到 <code>data/plugin_data/&lt;plugin&gt;/version-snapshots/</code>。管理端“插件管理 -&gt; 版本”可以查看经过 checksum 校验的快照并恢复。系统级插件随服务源码部署，只能通过代码版本回退并重启。</p><h2 id="版本门禁" tabindex="-1">版本门禁 <a class="header-anchor" href="#版本门禁" aria-label="Permalink to &quot;版本门禁&quot;">​</a></h2><p><code>make release-check</code> 运行路由合约、文档链接、Go 测试、migration、数据库体检、schema contract、三类插件模板、Web lint/format/build、Admin 与文档站构建、TypeScript SDK、恢复演练和 Chrome 页面 smoke。开发服务未启动时可显式设置 <code>RUN_BROWSER_SMOKE=false</code>，但正式验收不能跳过浏览器 smoke。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("operations/recovery.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const recovery = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  recovery as default
};
