import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"插件体系","description":"","frontmatter":{},"headers":[],"relativePath":"plugins/overview.md","filePath":"plugins/overview.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "plugins/overview.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="插件体系" tabindex="-1">插件体系 <a class="header-anchor" href="#插件体系" aria-label="Permalink to &quot;插件体系&quot;">​</a></h1><h2 id="插件是什么" tabindex="-1">插件是什么 <a class="header-anchor" href="#插件是什么" aria-label="Permalink to &quot;插件是什么&quot;">​</a></h2><p>CampusOS 插件是带有 <code>plugin.yaml</code> 的独立功能目录。Manager 通过 manifest 识别插件名称、版本、Runtime、事件、权限、存储和配置，再决定如何加载。</p><p>插件实现默认保存在：</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>data/plugins/&lt;plugin-name&gt;/</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>运行数据保存在：</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>data/plugin_data/&lt;plugin-name&gt;/</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>这两个目录不能混用。插件包可以更新代码，但不应覆盖用户数据。</p><h2 id="runtime" tabindex="-1">Runtime <a class="header-anchor" href="#runtime" aria-label="Permalink to &quot;Runtime&quot;">​</a></h2><h3 id="built-in" tabindex="-1">Built-in <a class="header-anchor" href="#built-in" aria-label="Permalink to &quot;Built-in&quot;">​</a></h3><p><code>runtime: builtin</code> 不启动外部进程。真实业务实现编译在 CampusOS 后端中，插件目录提供 manifest、配置和说明。</p><p>适合随系统交付且需要调用内部领域服务的能力，例如个人空间、课表、富文本和版主管理。</p><p>Built-in 不是允许第三方直接把任意 Go 代码放入目录后动态执行。增加新的 Built-in 能力通常仍需修改并重新编译 CampusOS。</p><h3 id="wasm" tabindex="-1">Wasm <a class="header-anchor" href="#wasm" aria-label="Permalink to &quot;Wasm&quot;">​</a></h3><p><code>runtime: wasm</code> 由 wazero 加载模块。插件通常包含：</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>plugin.yaml</span></span>
<span class="line"><span>plugin.wasm</span></span>
<span class="line"><span>README.md</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>适合小型事件处理和需要更强隔离的扩展。Wasm 插件只能通过声明并获准的 Host API 访问主系统。</p><h3 id="grpc" tabindex="-1">gRPC <a class="header-anchor" href="#grpc" aria-label="Permalink to &quot;gRPC&quot;">​</a></h3><p><code>runtime: grpc</code> 作为独立进程运行。适合复杂依赖、长任务或需要独立部署节奏的服务。</p><p>gRPC 插件必须说明启动命令、连接方式、超时和故障恢复要求。</p><h2 id="事件与-host-api" tabindex="-1">事件与 Host API <a class="header-anchor" href="#事件与-host-api" aria-label="Permalink to &quot;事件与 Host API&quot;">​</a></h2><p>插件可以订阅核心事件，例如：</p><div class="language-yaml vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">events</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  subscribe</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">thread.created</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">post.created</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>插件调用 Host API 前，Manager 会根据 manifest 权限检查：</p><div class="language-yaml vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">permissions</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  api</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">resource</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">log</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">      actions</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">write</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">]</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>权限默认拒绝。只声明当前功能需要的最小集合，不要使用“以后可能会用”为理由申请高风险权限。</p><h2 id="管理级别与生效方式" tabindex="-1">管理级别与生效方式 <a class="header-anchor" href="#管理级别与生效方式" aria-label="Permalink to &quot;管理级别与生效方式&quot;">​</a></h2><table tabindex="0"><thead><tr><th>字段</th><th>说明</th></tr></thead><tbody><tr><td><code>scope: system/user</code></td><td>管理级别、安装权限和系统重要性。</td></tr><tr><td><code>lifecycle.backend.activation_mode</code></td><td><code>restart</code>、<code>plugin-restart</code> 或 <code>hot</code>。</td></tr><tr><td><code>lifecycle.frontend.activation_mode</code></td><td>当前统一为 <code>hot</code>。</td></tr></tbody></table><p>这里的 <code>user</code> 不表示普通用户可以自行安装插件。安装、配置和更新仍属于管理员操作。系统级 gRPC 可以只重启插件，系统级 Wasm 可以热替换；具体行为不能再从 scope 推断。</p><h2 id="示例插件" tabindex="-1">示例插件 <a class="header-anchor" href="#示例插件" aria-label="Permalink to &quot;示例插件&quot;">​</a></h2><table tabindex="0"><thead><tr><th>插件</th><th>用途</th></tr></thead><tbody><tr><td><code>hello-wasm</code></td><td>最小可运行 Wasm 事件插件。</td></tr><tr><td><code>hello-plugin</code></td><td>gRPC manifest 示例。</td></tr><tr><td><code>campus-welcome</code></td><td>UI Runtime、声明式 Surface、Action 和 Extension Gateway 完整示例。</td></tr><tr><td><code>personal-space</code></td><td>Built-in 个人主页和用户文件能力。</td></tr><tr><td><code>homepage-customizer</code></td><td>Built-in 首页配置与风格包。</td></tr><tr><td><code>web-theme</code></td><td>Built-in 完整用户前台系统主题目录、用户本地选择和沙箱特效能力。</td></tr><tr><td><code>controlled-richtext-article</code></td><td>Built-in 富文本文章。</td></tr><tr><td><code>personal-schedule</code></td><td>Built-in 个人课表。</td></tr><tr><td><code>category-moderation</code></td><td>Built-in 版块版主管理。</td></tr></tbody></table><p>下一步：<a href="/plugins/create-first-plugin">编写第一个插件</a>。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("plugins/overview.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const overview = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  overview as default
};
