import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Go SDK、CLI 与本地测试","description":"","frontmatter":{},"headers":[],"relativePath":"plugins/sdk-cli.md","filePath":"plugins/sdk-cli.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "plugins/sdk-cli.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="go-sdk、cli-与本地测试" tabindex="-1">Go SDK、CLI 与本地测试 <a class="header-anchor" href="#go-sdk、cli-与本地测试" aria-label="Permalink to &quot;Go SDK、CLI 与本地测试&quot;">​</a></h1><h2 id="_10-分钟闭环" tabindex="-1">10 分钟闭环 <a class="header-anchor" href="#_10-分钟闭环" aria-label="Permalink to &quot;10 分钟闭环&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">go</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./cmd/campusosctl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> init</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> my-plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --runtime</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> grpc</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">go</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./cmd/campusosctl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> my-plugin</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">go</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./cmd/campusosctl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> my-plugin</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">go</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./cmd/campusosctl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> verify</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> my-plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --json</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">go</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./cmd/campusosctl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> plugin</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> pack</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> my-plugin</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p><code>plugin dev</code> 会依次执行 test、build 和 verify。CI 建议使用 <code>--json</code> 读取稳定结果，而不是解析人类输出。</p><h2 id="runtime-差异" tabindex="-1">Runtime 差异 <a class="header-anchor" href="#runtime-差异" aria-label="Permalink to &quot;Runtime 差异&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Runtime</th><th>build/test 行为</th><th>生命周期</th></tr></thead><tbody><tr><td>Built-in</td><td>校验 Manifest；代码随 CampusOS 编译测试</td><td>builtin+system 默认 <code>restart</code></td></tr><tr><td>gRPC process</td><td><code>go test ./...</code>、构建 <code>plugin</code> 可执行文件</td><td>默认 <code>plugin-restart</code></td></tr><tr><td>Wasm</td><td>检查 <code>plugin.wasm</code> 魔数和运行包</td><td>默认 <code>hot</code>，候选实例验证后交换</td></tr></tbody></table><p>当前 <code>grpc</code> 名称是兼容标识，进程事件传输尚未成为稳定 protobuf 契约。不要据此假设任意标准 gRPC 插件都能直接运行。</p><h2 id="mock-host" tabindex="-1">Mock Host <a class="header-anchor" href="#mock-host" aria-label="Permalink to &quot;Mock Host&quot;">​</a></h2><p>Go SDK 的 <code>NewHarness</code> 可注入配置、KV、用户、帖子、权限允许/拒绝、Host API 失败、日志、通知和事件，不需要启动完整服务器。HTTP 403 可通过 <code>errors.Is(err, campusos.ErrPermissionDenied)</code> 判断。</p><p>可运行模板位于 <code>examples/plugins/builtin-example</code>、<code>grpc-example</code> 和 <code>wasm-example</code>。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("plugins/sdk-cli.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const sdkCli = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  sdkCli as default
};
