import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"生命周期与数据","description":"","frontmatter":{},"headers":[],"relativePath":"plugins/lifecycle.md","filePath":"plugins/lifecycle.md","lastUpdated":1783761653000}');
const _sfc_main = { name: "plugins/lifecycle.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="生命周期与数据" tabindex="-1">生命周期与数据 <a class="header-anchor" href="#生命周期与数据" aria-label="Permalink to &quot;生命周期与数据&quot;">​</a></h1><p>CampusOS 不再用 <code>scope</code> 直接决定启停方式。<code>scope: system | user</code> 只描述管理级别、安装权限和系统重要性；后端和前端生效方式由 <code>lifecycle</code> 声明。</p><div class="language-yaml vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">lifecycle</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  backend</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    activation_mode</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">plugin-restart</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  frontend</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    activation_mode</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">hot</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h2 id="默认值" tabindex="-1">默认值 <a class="header-anchor" href="#默认值" aria-label="Permalink to &quot;默认值&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Runtime</th><th>后端</th><th>前端</th></tr></thead><tbody><tr><td>builtin + system</td><td><code>restart</code></td><td><code>hot</code></td></tr><tr><td>gRPC</td><td><code>plugin-restart</code></td><td><code>hot</code></td></tr><tr><td>Wasm</td><td><code>hot</code></td><td><code>hot</code></td></tr></tbody></table><p>旧 manifest 会自动得到这些默认值。系统级 gRPC 可以只重启插件；Wasm 使用候选实例验证成功后原子替换；Core 进程内 builtin 默认仍需整站重启。</p><h2 id="三轴状态" tabindex="-1">三轴状态 <a class="header-anchor" href="#三轴状态" aria-label="Permalink to &quot;三轴状态&quot;">​</a></h2><ul><li>BackendState：<code>installed / starting / running / restarting / stopping / stopped / pending_restart / error</code>。</li><li>FrontendState：<code>unloaded / loading / loaded / incompatible / error</code>。</li><li>Health：<code>healthy / degraded / unavailable / unknown</code>。</li></ul><p>后端短暂 restarting 或 degraded 时，前端页面不会消失。管理员明确停用或卸载插件后，Web 才清理其动态路由、导航、插槽、Surface 和 Action。旧 <code>status</code> 与 <code>pending_restart</code> 字段继续兼容。</p><h2 id="数据保留" tabindex="-1">数据保留 <a class="header-anchor" href="#数据保留" aria-label="Permalink to &quot;数据保留&quot;">​</a></h2><p>停止、禁用或热卸载前端不会自动删除 <code>data/plugin_data/&lt;plugin&gt;/</code>、PostgreSQL 配置和日志、用户业务数据或审计。系统级插件不能从 Admin 卸载；用户级插件卸载前应备份数据并阅读插件 README。</p><p>下一步阅读 <a href="./frontend-runtime">前端运行时与 Gateway</a>。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("plugins/lifecycle.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const lifecycle = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  lifecycle as default
};
