package v4

import (
	"archive/tar"
	"compress/gzip"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	ReleaseChecksumsFile       = "checksums.json"
	ReleaseSignatureFile       = "signature.json"
	maxPackageFiles            = 5000
	maxPackageBytes      int64 = 128 * 1024 * 1024
)

// ReleaseChecksums is generated by the packer rather than supplied by a
// plugin. Its entries cover every regular package file except itself and the
// detached signature; the latter signs this canonical manifest.
type ReleaseChecksums struct {
	Version string            `json:"version"`
	Files   map[string]string `json:"files"`
}

type ReleaseSignature struct {
	Algorithm string `json:"algorithm"`
	KeyID     string `json:"key_id"`
	Signature string `json:"signature"`
}

type PackageInfo struct {
	Manifest    *Manifest
	Digest      string
	ArchivePath string
	InstallPath string
	Files       []string
}

type InstallOptions struct {
	RootDir          string
	RequireSignature bool
	TrustedKeys      map[string]ed25519.PublicKey
}

// PrepareReleaseDirectory turns a validated source tree into a minimal,
// immutable release tree. It copies only the manifest, documentation,
// configuration definitions and the already-built dist output; source
// code, Node modules and a plugin's development files are never shipped.
// destination must be empty or absent, which prevents a build from mixing
// artifacts from different source revisions.
func PrepareReleaseDirectory(sourceRoot, destination string) (*Manifest, error) {
	manifest, err := ValidateSourceDirectory(sourceRoot)
	if err != nil {
		return nil, err
	}
	destination = filepath.Clean(destination)
	if info, statErr := os.Stat(destination); statErr == nil {
		if !info.IsDir() {
			return nil, errors.New("v4 release destination is not a directory")
		}
		entries, readErr := os.ReadDir(destination)
		if readErr != nil {
			return nil, readErr
		}
		if len(entries) != 0 {
			return nil, errors.New("v4 release destination must be empty")
		}
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return nil, statErr
	}
	if err := os.MkdirAll(destination, 0o700); err != nil {
		return nil, err
	}
	copyFiles := []string{"plugin.yaml", "README.md", "LICENSE"}
	for _, definition := range []*ConfigDefinition{manifest.Configuration.System, manifest.Configuration.User} {
		if definition != nil {
			copyFiles = append(copyFiles, definition.Schema, definition.Defaults)
		}
	}
	for _, relative := range copyFiles {
		if err := copyReleaseFile(sourceRoot, destination, relative); err != nil {
			return nil, err
		}
	}
	for _, artifact := range []*UIArtifact{manifest.Artifacts.UserUI, manifest.Artifacts.AdminUI} {
		if artifact == nil {
			continue
		}
		// Source UI directories are mapped to dist/<audience>. The
		// manifest still owns the final entry path, so it cannot choose a host
		// location or refer to a development file.
		audience := "user"
		if artifact == manifest.Artifacts.AdminUI {
			audience = "admin"
		}
		from := filepath.Join(sourceRoot, "dist", audience)
		to := filepath.Join(destination, filepath.FromSlash(path.Dir(artifact.Entry)))
		if err := copyReleaseDirectory(from, to); err != nil {
			return nil, fmt.Errorf("copy v4 %s UI build output: %w", audience, err)
		}
	}
	if _, err := ValidateReleaseDirectory(destination); err != nil {
		return nil, err
	}
	return manifest, nil
}

// BuildReleaseArchive writes a deterministic tar.gz release from a directory
// that already contains built UI entrypoints. It never runs package scripts.
func BuildReleaseArchive(releaseRoot, outputPath string) (*PackageInfo, error) {
	manifest, err := ValidateReleaseDirectory(releaseRoot)
	if err != nil {
		return nil, err
	}
	files, checksums, err := collectReleaseFiles(releaseRoot)
	if err != nil {
		return nil, err
	}
	checksumsData, err := canonicalJSON(ReleaseChecksums{Version: "campusos.release-checksums/v1", Files: checksums})
	if err != nil {
		return nil, err
	}
	if outputPath == "" {
		outputPath = filepath.Join(filepath.Dir(filepath.Clean(releaseRoot)), manifest.Key+"-"+manifest.Version+".tar.gz")
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return nil, err
	}
	file, err := os.Create(outputPath)
	if err != nil {
		return nil, err
	}
	archiveErr := writeReleaseArchive(file, releaseRoot, files, checksumsData, nil)
	closeErr := file.Close()
	if archiveErr != nil {
		_ = os.Remove(outputPath)
		return nil, archiveErr
	}
	if closeErr != nil {
		return nil, closeErr
	}
	digest, _, err := fileSHA256(outputPath)
	if err != nil {
		return nil, err
	}
	return &PackageInfo{Manifest: manifest, Digest: digest, ArchivePath: filepath.Clean(outputPath), Files: append([]string(nil), files...)}, nil
}

// SignReleaseArchive creates an adjacent detached signature package entry. A
// release archive is immutable, so signing produces a new archive instead of
// mutating the source directory or the original archive in place.
func SignReleaseArchive(archivePath, outputPath, keyID string, privateKey ed25519.PrivateKey) (*PackageInfo, error) {
	if strings.TrimSpace(keyID) == "" || len(privateKey) != ed25519.PrivateKeySize {
		return nil, errors.New("v4 release signature requires a key ID and Ed25519 private key")
	}
	tempDir, err := os.MkdirTemp("", "campusos-v4-release-sign-*")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tempDir)
	info, err := extractAndVerifyRelease(archivePath, tempDir, nil, false)
	if err != nil {
		return nil, err
	}
	checksums, err := os.ReadFile(filepath.Join(tempDir, ReleaseChecksumsFile))
	if err != nil {
		return nil, err
	}
	signature := ReleaseSignature{Algorithm: "ed25519", KeyID: keyID, Signature: base64.StdEncoding.EncodeToString(ed25519.Sign(privateKey, checksums))}
	signatureData, err := canonicalJSON(signature)
	if err != nil {
		return nil, err
	}
	files, _, err := collectReleaseFiles(tempDir)
	if err != nil {
		return nil, err
	}
	if outputPath == "" {
		outputPath = strings.TrimSuffix(archivePath, ".tar.gz") + ".signed.tar.gz"
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return nil, err
	}
	file, err := os.Create(outputPath)
	if err != nil {
		return nil, err
	}
	archiveErr := writeReleaseArchive(file, tempDir, files, checksums, signatureData)
	closeErr := file.Close()
	if archiveErr != nil {
		_ = os.Remove(outputPath)
		return nil, archiveErr
	}
	if closeErr != nil {
		return nil, closeErr
	}
	digest, _, err := fileSHA256(outputPath)
	if err != nil {
		return nil, err
	}
	info.Digest, info.ArchivePath = digest, filepath.Clean(outputPath)
	return info, nil
}

// InstallReleaseArchive verifies an archive inside .staging and atomically
// moves it to .installed/<key>/<version>-<digest>. It never executes files,
// runs install hooks or overwrites another digest for the same version.
func InstallReleaseArchive(archivePath string, options InstallOptions) (*PackageInfo, error) {
	root, err := installationRoot(options.RootDir)
	if err != nil {
		return nil, err
	}
	stagingRoot := filepath.Join(root, ".staging")
	installedRoot := filepath.Join(root, ".installed")
	if err := os.MkdirAll(stagingRoot, 0o700); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(installedRoot, 0o700); err != nil {
		return nil, err
	}
	stage, err := os.MkdirTemp(stagingRoot, "release-")
	if err != nil {
		return nil, err
	}
	keepStage := false
	defer func() {
		if !keepStage {
			_ = os.RemoveAll(stage)
		}
	}()
	info, err := extractAndVerifyRelease(archivePath, stage, options.TrustedKeys, options.RequireSignature)
	if err != nil {
		return nil, err
	}
	digest, _, err := fileSHA256(archivePath)
	if err != nil {
		return nil, err
	}
	keyRoot := filepath.Join(installedRoot, info.Manifest.Key)
	if err := os.MkdirAll(keyRoot, 0o700); err != nil {
		return nil, err
	}
	name := info.Manifest.Version + "-" + strings.TrimPrefix(digest, "sha256:")[:16]
	target := filepath.Join(keyRoot, name)
	if existing, statErr := os.Stat(target); statErr == nil {
		if !existing.IsDir() {
			return nil, errors.New("v4 install target is not a directory")
		}
		info.Digest, info.ArchivePath, info.InstallPath = digest, filepath.Clean(archivePath), target
		return info, nil
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return nil, statErr
	}
	if err := os.Rename(stage, target); err != nil {
		return nil, fmt.Errorf("atomically install v4 release: %w", err)
	}
	keepStage = true
	info.Digest, info.ArchivePath, info.InstallPath = digest, filepath.Clean(archivePath), target
	return info, nil
}

func installationRoot(value string) (string, error) {
	if strings.TrimSpace(value) == "" {
		value = "plugins"
	}
	root, err := filepath.Abs(filepath.Clean(value))
	if err != nil {
		return "", err
	}
	return root, nil
}

func collectReleaseFiles(root string) ([]string, map[string]string, error) {
	files := []string{}
	checksums := map[string]string{}
	var total int64
	err := filepath.WalkDir(root, func(current string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if current == root {
			return nil
		}
		rel, err := filepath.Rel(root, current)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if !safeRelativePath(rel) {
			return fmt.Errorf("v4 release path is unsafe: %s", rel)
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("v4 release does not permit symbolic links: %s", rel)
		}
		if entry.IsDir() {
			return nil
		}
		if !entry.Type().IsRegular() {
			return fmt.Errorf("v4 release only permits regular files: %s", rel)
		}
		if rel == ReleaseChecksumsFile || rel == ReleaseSignatureFile {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		total += info.Size()
		if len(files) >= maxPackageFiles || total > maxPackageBytes {
			return errors.New("v4 release exceeds package file or byte limit")
		}
		digest, _, err := fileSHA256(current)
		if err != nil {
			return err
		}
		files = append(files, rel)
		checksums[rel] = digest
		return nil
	})
	if err != nil {
		return nil, nil, err
	}
	sort.Strings(files)
	return files, checksums, nil
}

func writeReleaseArchive(destination io.Writer, root string, files []string, checksums, signature []byte) error {
	gzipWriter := gzip.NewWriter(destination)
	tarWriter := tar.NewWriter(gzipWriter)
	for _, rel := range files {
		if err := writeArchiveFile(tarWriter, filepath.Join(root, filepath.FromSlash(rel)), rel); err != nil {
			_ = tarWriter.Close()
			_ = gzipWriter.Close()
			return err
		}
	}
	if err := writeArchiveBytes(tarWriter, ReleaseChecksumsFile, checksums); err != nil {
		_ = tarWriter.Close()
		_ = gzipWriter.Close()
		return err
	}
	if signature != nil {
		if err := writeArchiveBytes(tarWriter, ReleaseSignatureFile, signature); err != nil {
			_ = tarWriter.Close()
			_ = gzipWriter.Close()
			return err
		}
	}
	if err := tarWriter.Close(); err != nil {
		_ = gzipWriter.Close()
		return err
	}
	return gzipWriter.Close()
}

func writeArchiveFile(writer *tar.Writer, filename, rel string) error {
	info, err := os.Stat(filename)
	if err != nil {
		return err
	}
	header := &tar.Header{Name: rel, Mode: 0o644, Size: info.Size(), ModTime: time.Unix(0, 0).UTC(), Format: tar.FormatPAX}
	if err := writer.WriteHeader(header); err != nil {
		return err
	}
	input, err := os.Open(filename)
	if err != nil {
		return err
	}
	defer input.Close()
	_, err = io.Copy(writer, input)
	return err
}

func writeArchiveBytes(writer *tar.Writer, rel string, data []byte) error {
	if err := writer.WriteHeader(&tar.Header{Name: rel, Mode: 0o644, Size: int64(len(data)), ModTime: time.Unix(0, 0).UTC(), Format: tar.FormatPAX}); err != nil {
		return err
	}
	_, err := writer.Write(data)
	return err
}

func extractAndVerifyRelease(archivePath, destination string, trusted map[string]ed25519.PublicKey, requireSignature bool) (*PackageInfo, error) {
	archive, err := os.Open(archivePath)
	if err != nil {
		return nil, err
	}
	defer archive.Close()
	gzipReader, err := gzip.NewReader(archive)
	if err != nil {
		return nil, fmt.Errorf("read v4 release gzip: %w", err)
	}
	defer gzipReader.Close()
	tarReader := tar.NewReader(gzipReader)
	seen := map[string]bool{}
	var count int
	var total int64
	for {
		header, err := tarReader.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("read v4 release archive: %w", err)
		}
		if header.Typeflag != tar.TypeReg || !safeRelativePath(header.Name) || seen[header.Name] || header.Size < 0 {
			return nil, errors.New("v4 release archive has an unsafe entry")
		}
		count++
		total += header.Size
		if count > maxPackageFiles+2 || total > maxPackageBytes+512*1024 {
			return nil, errors.New("v4 release archive exceeds package file or byte limit")
		}
		seen[header.Name] = true
		target := filepath.Join(destination, filepath.FromSlash(header.Name))
		if err := ensureContainedPath(destination, target); err != nil {
			return nil, err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
			return nil, err
		}
		output, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
		if err != nil {
			return nil, err
		}
		_, copyErr := io.Copy(output, io.LimitReader(tarReader, header.Size))
		closeErr := output.Close()
		if copyErr != nil || closeErr != nil {
			return nil, errors.Join(copyErr, closeErr)
		}
	}
	manifest, err := ValidateReleaseDirectory(destination)
	if err != nil {
		return nil, err
	}
	checksumsData, err := os.ReadFile(filepath.Join(destination, ReleaseChecksumsFile))
	if err != nil {
		return nil, errors.New("v4 release is missing checksums.json")
	}
	var checksums ReleaseChecksums
	if err := json.Unmarshal(checksumsData, &checksums); err != nil || checksums.Version != "campusos.release-checksums/v1" {
		return nil, errors.New("v4 release checksums are invalid")
	}
	files, calculated, err := collectReleaseFiles(destination)
	if err != nil {
		return nil, err
	}
	if !sameChecksums(checksums.Files, calculated) {
		return nil, errors.New("v4 release checksum verification failed")
	}
	if err := verifyReleaseSignature(destination, checksumsData, trusted, requireSignature); err != nil {
		return nil, err
	}
	return &PackageInfo{Manifest: manifest, Files: files}, nil
}

func verifyReleaseSignature(root string, checksums []byte, trusted map[string]ed25519.PublicKey, required bool) error {
	data, err := os.ReadFile(filepath.Join(root, ReleaseSignatureFile))
	if errors.Is(err, os.ErrNotExist) && !required {
		return nil
	}
	if err != nil {
		return errors.New("v4 release signature is required")
	}
	var signature ReleaseSignature
	if json.Unmarshal(data, &signature) != nil || signature.Algorithm != "ed25519" || signature.KeyID == "" {
		return errors.New("v4 release signature is invalid")
	}
	publicKey, ok := trusted[signature.KeyID]
	if !ok || len(publicKey) != ed25519.PublicKeySize {
		return errors.New("v4 release signing key is not trusted")
	}
	decoded, err := base64.StdEncoding.DecodeString(signature.Signature)
	if err != nil || !ed25519.Verify(publicKey, checksums, decoded) {
		return errors.New("v4 release signature verification failed")
	}
	return nil
}

func sameChecksums(want, got map[string]string) bool {
	if len(want) != len(got) {
		return false
	}
	for name, value := range want {
		if got[name] != value {
			return false
		}
	}
	return true
}

func fileSHA256(filename string) (string, int64, error) {
	input, err := os.Open(filename)
	if err != nil {
		return "", 0, err
	}
	defer input.Close()
	hash := sha256.New()
	size, err := io.Copy(hash, input)
	if err != nil {
		return "", 0, err
	}
	return "sha256:" + hex.EncodeToString(hash.Sum(nil)), size, nil
}

func canonicalJSON(value any) ([]byte, error) {
	data, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func copyReleaseFile(sourceRoot, destination, relative string) error {
	if !safeRelativePath(relative) {
		return errors.New("v4 release copy path is unsafe")
	}
	from := filepath.Join(sourceRoot, filepath.FromSlash(relative))
	to := filepath.Join(destination, filepath.FromSlash(relative))
	if err := ensureContainedPath(destination, to); err != nil {
		return err
	}
	info, err := os.Lstat(from)
	if err != nil || info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return errors.New("v4 release source file is unsafe")
	}
	if err := os.MkdirAll(filepath.Dir(to), 0o700); err != nil {
		return err
	}
	input, err := os.Open(from)
	if err != nil {
		return err
	}
	defer input.Close()
	output, err := os.OpenFile(to, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	_, copyErr := io.Copy(output, input)
	closeErr := output.Close()
	return errors.Join(copyErr, closeErr)
}

func copyReleaseDirectory(sourceRoot, destination string) error {
	info, err := os.Lstat(sourceRoot)
	if err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("v4 release UI output directory is missing or unsafe")
	}
	return filepath.WalkDir(sourceRoot, func(current string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(sourceRoot, current)
		if err != nil {
			return err
		}
		if rel == "." {
			return os.MkdirAll(destination, 0o700)
		}
		rel = filepath.ToSlash(rel)
		if !safeRelativePath(rel) || entry.Type()&os.ModeSymlink != 0 {
			return errors.New("v4 release UI output contains an unsafe path")
		}
		target := filepath.Join(destination, filepath.FromSlash(rel))
		if entry.IsDir() {
			return os.MkdirAll(target, 0o700)
		}
		if !entry.Type().IsRegular() {
			return errors.New("v4 release UI output must contain regular files")
		}
		return copyReleaseFileFromPath(current, target)
	})
}

func copyReleaseFileFromPath(from, to string) error {
	if err := os.MkdirAll(filepath.Dir(to), 0o700); err != nil {
		return err
	}
	input, err := os.Open(from)
	if err != nil {
		return err
	}
	defer input.Close()
	output, err := os.OpenFile(to, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	_, copyErr := io.Copy(output, input)
	closeErr := output.Close()
	return errors.Join(copyErr, closeErr)
}

func ensureContainedPath(root, target string) error {
	rootAbs, err := filepath.Abs(filepath.Clean(root))
	if err != nil {
		return err
	}
	targetAbs, err := filepath.Abs(filepath.Clean(target))
	if err != nil || (targetAbs != rootAbs && !strings.HasPrefix(targetAbs, rootAbs+string(filepath.Separator))) {
		return errors.New("v4 release archive path escapes destination")
	}
	return nil
}
